{"cells":[{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":25521,"status":"ok","timestamp":1699535766828,"user":{"displayName":"이주형","userId":"07579585688851948048"},"user_tz":-540},"id":"FdZnDI8azinw","outputId":"40d4ef68-872b-4c0b-9eb3-440e69ef6818"},"outputs":[{"name":"stdout","output_type":"stream","text":["Mounted at /gdrive\n"]}],"source":["from google.colab import drive\n","drive.mount(\"/gdrive\", force_remount=True)"]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"background_save":true,"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":319,"status":"ok","timestamp":1699539988975,"user":{"displayName":"이주형","userId":"07579585688851948048"},"user_tz":-540},"id":"fKVf5EjqC0bJ","outputId":"d463d809-8802-42fc-c1ac-b9a061ecd47b"},"outputs":[{"name":"stdout","output_type":"stream","text":["shell-init: error retrieving current directory: getcwd: cannot access parent directories: Transport endpoint is not connected\n","mkdir: cannot create directory ‘/gdrive/MyDrive/Colab/Week11/libs’: File exists\n"]},{"name":"stderr","output_type":"stream","text":["ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n"]},{"name":"stdout","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-34-aa3ca716be2a>\", line 2, in <cell line: 2>\n","    get_ipython().run_line_magic('cd', '/gdrive/MyDrive/Colab/Week11/libs')\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2418, in run_line_magic\n","    result = fn(*args, **kwargs)\n","  File \"<decorator-gen-85>\", line 2, in cd\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/magic.py\", line 187, in <lambda>\n","    call = lambda f, *a, **k: f(*a, **k)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/magics/osm.py\", line 342, in cd\n","    oldcwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-34-aa3ca716be2a>\", line 2, in <cell line: 2>\n","    get_ipython().run_line_magic('cd', '/gdrive/MyDrive/Colab/Week11/libs')\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2418, in run_line_magic\n","    result = fn(*args, **kwargs)\n","  File \"<decorator-gen-85>\", line 2, in cd\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/magic.py\", line 187, in <lambda>\n","    call = lambda f, *a, **k: f(*a, **k)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/magics/osm.py\", line 342, in cd\n","    oldcwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-34-aa3ca716be2a>\", line 2, in <cell line: 2>\n","    get_ipython().run_line_magic('cd', '/gdrive/MyDrive/Colab/Week11/libs')\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2418, in run_line_magic\n","    result = fn(*args, **kwargs)\n","  File \"<decorator-gen-85>\", line 2, in cd\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/magic.py\", line 187, in <lambda>\n","    call = lambda f, *a, **k: f(*a, **k)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/magics/osm.py\", line 342, in cd\n","    oldcwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3030, in _run_cell\n","    return runner(coro)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/async_helpers.py\", line 78, in _pseudo_sync_runner\n","    coro.send(None)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3257, in run_cell_async\n","    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3492, in run_ast_nodes\n","    self.showtraceback()\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1142, in structured_traceback\n","    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n"]}],"source":["%mkdir /gdrive/MyDrive/Colab/Week11/libs\n","%cd /gdrive/MyDrive/Colab/Week11/libs"]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"background_save":true,"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":31828,"status":"ok","timestamp":1699540022319,"user":{"displayName":"이주형","userId":"07579585688851948048"},"user_tz":-540},"id":"eeuQLlBKJsER","outputId":"73a7b234-448e-4d32-bf18-a1273544f93f"},"outputs":[{"name":"stdout","output_type":"stream","text":["shell-init: error retrieving current directory: getcwd: cannot access parent directories: Transport endpoint is not connected\n","fatal: could not create work tree dir 'wordvectors': Transport endpoint is not connected\n"]},{"name":"stderr","output_type":"stream","text":["ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n"]},{"name":"stdout","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-33-264203decea7>\", line 2, in <cell line: 2>\n","    get_ipython().run_line_magic('cd', 'Mecab-ko-for-Google-Colab')\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2418, in run_line_magic\n","    result = fn(*args, **kwargs)\n","  File \"<decorator-gen-85>\", line 2, in cd\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/magic.py\", line 187, in <lambda>\n","    call = lambda f, *a, **k: f(*a, **k)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/magics/osm.py\", line 342, in cd\n","    oldcwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-33-264203decea7>\", line 2, in <cell line: 2>\n","    get_ipython().run_line_magic('cd', 'Mecab-ko-for-Google-Colab')\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2418, in run_line_magic\n","    result = fn(*args, **kwargs)\n","  File \"<decorator-gen-85>\", line 2, in cd\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/magic.py\", line 187, in <lambda>\n","    call = lambda f, *a, **k: f(*a, **k)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/magics/osm.py\", line 342, in cd\n","    oldcwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-33-264203decea7>\", line 2, in <cell line: 2>\n","    get_ipython().run_line_magic('cd', 'Mecab-ko-for-Google-Colab')\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2418, in run_line_magic\n","    result = fn(*args, **kwargs)\n","  File \"<decorator-gen-85>\", line 2, in cd\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/magic.py\", line 187, in <lambda>\n","    call = lambda f, *a, **k: f(*a, **k)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/magics/osm.py\", line 342, in cd\n","    oldcwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3030, in _run_cell\n","    return runner(coro)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/async_helpers.py\", line 78, in _pseudo_sync_runner\n","    coro.send(None)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3257, in run_cell_async\n","    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3492, in run_ast_nodes\n","    self.showtraceback()\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1142, in structured_traceback\n","    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n"]}],"source":["!git clone https://github.com/Kyubyong/wordvectors\n","%cd Mecab-ko-for-Google-Colab\n","!bash install_mecab-ko_on_colab_light_220429.sh\n","%cd .."]},{"cell_type":"code","execution_count":34,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":6,"status":"ok","timestamp":1699541442650,"user":{"displayName":"이주형","userId":"07579585688851948048"},"user_tz":-540},"id":"z8njZiU_y1VI","outputId":"fd0cf0ff-ffc4-41aa-8f48-1f979be3572a"},"outputs":[{"output_type":"stream","name":"stdout","text":["tensor(0.5000)\n"]}],"source":["import torch\n","\n","NLP = torch.FloatTensor([0,1,0,0,0,0,0,1])\n","learning = torch.FloatTensor([0,0,0,1,0,0,0,1])\n","\n","print(torch.cosine_similarity(NLP, learning, dim=0))"]},{"cell_type":"code","execution_count":2,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":556,"status":"ok","timestamp":1699541512205,"user":{"displayName":"이주형","userId":"07579585688851948048"},"user_tz":-540},"id":"5-Yj5-JyNCLs","outputId":"7e8015c3-aadf-4ef2-a62d-c45c07765060"},"outputs":[{"output_type":"stream","name":"stdout","text":["[('기계', 'NNG'), ('학습', 'NNG'), ('을', 'JKO'), ('위한', 'VV+ETM'), ('텍스트', 'NNG'), ('처리', 'NNG'), ('방법', 'NNG'), ('을', 'JKO'), ('공부', 'NNG'), ('해', 'XSV+EC'), ('보', 'VX'), ('자', 'EF'), ('.', 'SF')]\n","[('기계', 'NNG'), ('학습', 'NNG'), ('을', 'JKO'), ('위한', 'VV+ETM'), ('텍스트', 'NNG'), ('처리', 'NNG'), ('방법', 'NNG'), ('을', 'JKO'), ('공부', 'NNG'), ('해', 'XSV+EC'), ('보', 'VX'), ('자', 'EF'), ('.', 'SF')]\n"]}],"source":["from konlpy.tag import Mecab\n","\n","m = Mecab()\n","res = m.pos(\"기계학습을 위한 텍스트 처리 방법을 공부해보자.\")\n","print(res)"]},{"cell_type":"code","execution_count":3,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":1487,"status":"ok","timestamp":1699541517307,"user":{"displayName":"이주형","userId":"07579585688851948048"},"user_tz":-540},"id":"cKPBvjGsSTzm","outputId":"fc8df5ae-548b-4c5f-edeb-7bc4730eda5d"},"outputs":[{"output_type":"stream","name":"stdout","text":["사전 크기: 24\n","7 0\n","나 unk\n"]}],"source":["from konlpy.tag import Mecab\n","from nltk import FreqDist\n","import numpy as np\n","\n","def make_dic(texts):\n","\n","  words = []\n","  m = Mecab()\n","\n","  for snt in texts:\n","    res = m.pos(snt)\n","    for (lex,pos) in res:\n","      if pos[0] == 'N' or pos[0] == 'V':\n","        words.append(lex)\n","\n","  # 단어의 빈도수 계산\n","  dic = FreqDist(np.hstack(words))\n","  print('사전 크기: {0:d}'.format(len(dic)))\n","\n","  # 인덱스를 저장할 변수 초기화\n","  indexes = {}\n","  words = {}\n","\n","  # 단어에 고유 번호(인덱스) 부여\n","  for num, word in enumerate(dic):\n","    idx = num+2\n","    indexes[word]= idx\n","    words[idx] = word\n","\n","  # 문장 길이 정규화에 사용한 패딩 인덱스\n","  indexes['pad'] = 1\n","  words[1] = 'pad'\n","  # 사전에 없는 단어에 대한 인덱스\n","  indexes['unk'] = 0\n","  words[0] = 'unk'\n","\n","  return (indexes, words)\n","\n","def word2index(indexes, word):\n","  idx = indexes[word] if word in indexes else indexes['unk']\n","  return idx\n","\n","def index2word(words, index):\n","  w = words[index] if index in words else -1\n","  return w\n","\n","texts = [\"죽는 날까지 하늘을 우러러 한 점 부끄럼이 없기를\",\n","         \"잎새에 이는 바람에도 나는 괴로워 했다.\",\n","         \"별을 노래하는 마음으로 모든 죽어 가는 것을 사랑해야지\",\n","         \"그리고 나한테 주어진 길을 걸어가야겠다.\",\n","         \"오늘 밤에도 별이 바람에 스치운다.\"]\n","\n","(indexes, words) = make_dic(texts)\n","\n","print(word2index(indexes,'하늘'), word2index(indexes,'학교'))\n","print(index2word(words,4), index2word(words,0))"]},{"cell_type":"code","execution_count":4,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":358,"status":"ok","timestamp":1699541530167,"user":{"displayName":"이주형","userId":"07579585688851948048"},"user_tz":-540},"id":"yeTswZzN5YyU","outputId":"5d0cd1a8-7264-4717-9b87-b0ca5aff80fa"},"outputs":[{"output_type":"stream","name":"stdout","text":["[['날', '하늘', '점', '부끄럼'], ['잎새', '바람', '나'], ['별', '노래', '마음', '것', '사랑'], ['나', '길'], ['밤', '별', '바람']] \n","\n","[ 0.02348376 -0.04519032  0.08388732 -0.09858163  0.06764641  0.02914417\n"," -0.04932832  0.04398187 -0.01739575  0.06711384]\n","[('잎새', 0.5111488699913025), ('날', 0.43408337235450745), ('것', 0.3862057030200958), ('바람', 0.3002755343914032), ('길', 0.141779825091362), ('밤', 0.057554230093955994), ('마음', -0.027840567752718925), ('사랑', -0.05887392535805702), ('부끄럼', -0.09835173189640045), ('점', -0.10117148607969284)] \n","\n","[ 0.02348376 -0.04519032  0.08388732 -0.09858163  0.06764641  0.02914417\n"," -0.04932832  0.04398187 -0.01739575  0.06711384]\n","[('잎새', 0.5111488699913025), ('날', 0.43408337235450745), ('것', 0.3862057030200958), ('바람', 0.3002755343914032), ('길', 0.141779825091362), ('밤', 0.057554230093955994), ('마음', -0.027840567752718925), ('사랑', -0.05887392535805702), ('부끄럼', -0.09835173189640045), ('점', -0.10117148607969284)]\n"]}],"source":["from konlpy.tag import Mecab\n","import numpy as np\n","from gensim.models import Word2Vec, KeyedVectors\n","\n","texts = [\"죽는 날까지 하늘을 우러러 한 점 부끄럼이 없기를\",\n","         \"잎새에 이는 바람에도 나는 괴로워 했다.\",\n","         \"별을 노래하는 마음으로 모든 죽어 가는 것을 사랑해야지\",\n","         \"그리고 나한테 주어진 길을 걸어가야겠다.\",\n","         \"오늘 밤에도 별이 바람에 스치운다.\"]\n","\n","# Word2Vec 학습에 사용할 데이터 만들기\n","\n","m = Mecab()\n","result = []\n","\n","for sent in texts:\n","  tag = m.pos(sent)\n","  words = []\n","  for (lex,pos) in tag:\n","    if pos[0] == 'N':\n","      words.append(lex)\n","  result.append(words)\n","\n","print(result,\"\\n\")\n","\n","# Word2Vec 학습시키기\n","model = Word2Vec(sentences=result, vector_size=10, window=1, min_count=1, workers=1, sg=0)\n","\n","# 값 읽어오기\n","print(model.wv['하늘'])\n","# 유사한 단어 가져오기\n","print(model.wv.most_similar(\"하늘\"),\"\\n\")\n","\n","# Word2Vec 모델 저장하기\n","model.wv.save_word2vec_format('/gdrive/MyDrive/Colab/Week11/libs/wordvectors/test_w2v')\n","\n","# Word2Vec 모델 로드하기\n","loaded_model = KeyedVectors.load_word2vec_format(\"/gdrive/MyDrive/Colab/Week11/libs/wordvectors/test_w2v\")\n","\n","# 값 읽어오기\n","print(loaded_model['하늘'])\n","\n","# 유사한 단어 가져오기\n","print(loaded_model.most_similar(\"하늘\"))"]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":27664,"status":"ok","timestamp":1699536013337,"user":{"displayName":"이주형","userId":"07579585688851948048"},"user_tz":-540},"id":"hZmC8MFZELmp","outputId":"9b38c2c2-8fe5-4168-fe47-c3c1b00f12fe"},"outputs":[{"name":"stdout","output_type":"stream","text":["Collecting glove-python3\n","  Downloading glove_python3-0.1.0.tar.gz (326 kB)\n","\u001b[?25l     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m0.0/327.0 kB\u001b[0m \u001b[31m?\u001b[0m eta \u001b[36m-:--:--\u001b[0m\r\u001b[2K     \u001b[91m━━━━━\u001b[0m\u001b[90m╺\u001b[0m\u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m41.0/327.0 kB\u001b[0m \u001b[31m1.4 MB/s\u001b[0m eta \u001b[36m0:00:01\u001b[0m\r\u001b[2K     \u001b[91m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[91m╸\u001b[0m\u001b[90m━\u001b[0m \u001b[32m317.4/327.0 kB\u001b[0m \u001b[31m5.5 MB/s\u001b[0m eta \u001b[36m0:00:01\u001b[0m\r\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m327.0/327.0 kB\u001b[0m \u001b[31m4.6 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25l\u001b[?25hdone\n","Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from glove-python3) (1.23.5)\n","Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from glove-python3) (1.11.3)\n","Building wheels for collected packages: glove-python3\n","  Building wheel for glove-python3 (setup.py) ... \u001b[?25l\u001b[?25hdone\n","  Created wheel for glove-python3: filename=glove_python3-0.1.0-cp310-cp310-linux_x86_64.whl size=1065519 sha256=7012dbccf0b1b930b1c5bfc3df1eeed56d2dd18c2203f0fc1f07989841e35804\n","  Stored in directory: /root/.cache/pip/wheels/fe/2f/79/34314d44a0907e90e323c8c182ec23f126eb460829e02d98cf\n","Successfully built glove-python3\n","Installing collected packages: glove-python3\n","Successfully installed glove-python3-0.1.0\n"]}],"source":["# colab 환경에 glove 설치\n","# !pip install glove-python-binary\n","!pip install glove-python3  ### 에러 수정"]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":5,"status":"ok","timestamp":1699536013337,"user":{"displayName":"이주형","userId":"07579585688851948048"},"user_tz":-540},"id":"pLqHcIyLFIS5","outputId":"1146bec3-5117-493a-f7ff-cc0954f85752"},"outputs":[{"name":"stdout","output_type":"stream","text":["[['날', '하늘', '점', '부끄럼'], ['잎새', '바람', '나'], ['별', '노래', '마음', '것', '사랑'], ['나', '길'], ['밤', '별', '바람']] \n","\n","Performing 20 training epochs with 1 threads\n","Epoch 0\n","Epoch 1\n","Epoch 2\n","Epoch 3\n","Epoch 4\n","Epoch 5\n","Epoch 6\n","Epoch 7\n","Epoch 8\n","Epoch 9\n","Epoch 10\n","Epoch 11\n","Epoch 12\n","Epoch 13\n","Epoch 14\n","Epoch 15\n","Epoch 16\n","Epoch 17\n","Epoch 18\n","Epoch 19\n","[ 0.00384011 -0.02970212 -0.04078236 -0.0247333  -0.04349602  0.01626312\n"," -0.01928094 -0.01770437  0.03715702 -0.03550971]\n","[('점', 0.5737224399373443), ('마음', 0.3115480865546868), ('날', 0.03946892686918532), ('별', 0.02659044244531927)] \n","\n","[ 0.00384011 -0.02970212 -0.04078236 -0.0247333  -0.04349602  0.01626312\n"," -0.01928094 -0.01770437  0.03715702 -0.03550971]\n","[('점', 0.5737224399373443), ('마음', 0.3115480865546868), ('날', 0.03946892686918532), ('별', 0.02659044244531927)]\n"]}],"source":["from konlpy.tag import Mecab\n","import numpy as np\n","from glove import Corpus, Glove\n","\n","texts = [\"죽는 날까지 하늘을 우러러 한 점 부끄럼이 없기를\",\n","         \"잎새에 이는 바람에도 나는 괴로워 했다.\",\n","         \"별을 노래하는 마음으로 모든 죽어 가는 것을 사랑해야지\",\n","         \"그리고 나한테 주어진 길을 걸어가야겠다.\",\n","         \"오늘 밤에도 별이 바람에 스치운다.\"]\n","\n","# GloVe 학습에 사용할 데이터 만들기\n","\n","m = Mecab()\n","result = []\n","\n","for sent in texts:\n","  tag = m.pos(sent)\n","  words = []\n","  for (lex,pos) in tag:\n","    if pos[0] == 'N':\n","      words.append(lex)\n","  result.append(words)\n","\n","print(result,\"\\n\")\n","\n","# Co-Occurrence Matrix 생성\n","corpus = Corpus()\n","corpus.fit(result, window=1)\n","\n","# GloVe 학습시키기\n","glove = Glove(no_components=10, learning_rate=0.05)\n","glove.fit(corpus.matrix, epochs=20, no_threads=1, verbose=True)\n","glove.add_dictionary(corpus.dictionary)\n","\n","# 값 읽어오기\n","print(glove.word_vectors[glove.dictionary['하늘']])\n","# 유사한 단어 가져오기\n","print(glove.most_similar(\"하늘\"),\"\\n\")\n","\n","# GloVe 모델 저장하기\n","glove.save('/gdrive/MyDrive/Colab/Week11/libs/test_glove')\n","\n","# GloVe 모델 로드하기\n","loaded_model = glove.load(\"/gdrive/MyDrive/Colab/Week11/libs/test_glove\")\n","\n","# 값 읽어오기\n","print(loaded_model.word_vectors[glove.dictionary['하늘']])\n","# 유사한 단어 가져오기\n","print(loaded_model.most_similar(\"하늘\"))"]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":6,"status":"ok","timestamp":1699536017468,"user":{"displayName":"이주형","userId":"07579585688851948048"},"user_tz":-540},"id":"fni57myGQpjO","outputId":"a7e57dd3-91c9-4097-8c1b-235c8a2946a9"},"outputs":[{"name":"stdout","output_type":"stream","text":["{'flying': 2, 'like': 3, 'I': 4, 'NLP': 5, 'deep': 6, 'learning': 7, 'enjoy': 8, 'unk': 0, 'pad': 1}\n","tensor([[0.1000, 0.8000, 0.7000],\n","        [0.7000, 0.8000, 0.2000],\n","        [0.0000, 0.0000, 0.0000]])\n","Parameter containing:\n","tensor([[-0.6809,  0.2274,  0.8710],\n","        [ 0.0000,  0.0000,  0.0000],\n","        [-1.7034,  1.3428, -1.7806],\n","        [-0.8012, -0.5668, -0.5174],\n","        [ 0.9463, -0.7362, -0.2316],\n","        [-0.5462, -0.5778,  0.7605],\n","        [ 1.1677,  0.0356,  0.4866],\n","        [ 0.3538,  0.5807,  0.2744],\n","        [ 0.4247, -0.6811,  1.3364]], requires_grad=True)\n"]}],"source":["import torch\n","import torch.nn as nn\n","\n","train_data = 'I like deep learning I like NLP I enjoy flying'\n","\n","# 중복을 제거한 단어들의 집합인 단어 집합 생성.\n","word_set = set(train_data.split())\n","\n","# 단어 집합의 각 단어에 고유한 정수 맵핑\n","vocab = {word: i+2 for i, word in enumerate(word_set)}\n","vocab['unk'] = 0\n","vocab['pad'] = 1\n","print(vocab)\n","\n","# 임베딩 테이블: (단어수, 임베딩 사이즈)\n","embedding_table = torch.FloatTensor([[ 0.0,  0.0,  0.0],\n","                                     [ 0.0,  0.0,  0.0],\n","                                     [ 0.1,  0.8,  0.3],\n","                                     [ 0.7,  0.8,  0.2],\n","                                     [ 0.1,  0.8,  0.7],\n","                                     [ 0.9,  0.2,  0.1],\n","                                     [ 0.1,  0.1,  0.9],\n","                                     [ 0.2,  0.1,  0.7],\n","                                     [ 0.3,  0.1,  0.1]])\n","\n","# 입력 문장\n","input_snt = 'I like football'.split()\n","\n","# 각 단어를 정수로 변환\n","idxes=[]\n","\n","for word in input_snt:\n","  idx = vocab[word] if word in vocab else vocab['unk']\n","  idxes.append(idx)\n","\n","idxes = torch.LongTensor(idxes)\n","\n","# 입력 문장의임베딩가져오기: ['I', 'like', 'football (unk)']\n","lookup_result = embedding_table[idxes, :]\n","print(lookup_result)\n","\n","# 임베딩 층 만들기\n","embedding_layer = nn.Embedding(num_embeddings=len(vocab), embedding_dim=3, padding_idx=1)\n","print(embedding_layer.weight)"]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":15121,"status":"ok","timestamp":1699536035212,"user":{"displayName":"이주형","userId":"07579585688851948048"},"user_tz":-540},"id":"-X2Ksgb6jMvn","outputId":"c8fa94ab-e607-43a4-9056-62ddc1e2b422"},"outputs":[{"name":"stdout","output_type":"stream","text":["Collecting sentencepiece\n","  Downloading sentencepiece-0.1.99-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)\n","\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m1.3/1.3 MB\u001b[0m \u001b[31m5.0 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25hInstalling collected packages: sentencepiece\n","Successfully installed sentencepiece-0.1.99\n"]}],"source":["!pip install sentencepiece"]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":418,"status":"ok","timestamp":1699536058352,"user":{"displayName":"이주형","userId":"07579585688851948048"},"user_tz":-540},"id":"jYcRu50-lfIe","outputId":"2ddfaf5c-cb98-44bd-f894-d24e00437b57"},"outputs":[{"name":"stdout","output_type":"stream","text":["['▁', '하', '늘', '을', '▁우', '러', '러']\n","[174, 193, 356, 186, 80, 315, 315]\n","하늘을 우러러\n","하늘을 우러러\n","Vocab. Size = 500\n","▁강\n","193\n"]}],"source":["import sentencepiece as spm\n","\n","input_file = \"/gdrive/MyDrive/Colab/Week11/corpus.txt\"\n","vocab_size = 500\n","model_name = 'subword_kor'\n","model_type = 'bpe'\n","user_defined_symbols = '[PAD],[UNK],[CLS],[SEP],[MASK],[UNK1],[UNK2],[UNK3],[UNK4],[UNK5]'\n","\n","input_argument = '--input=%s --model_prefix=%s --vocab_size=%s --user_defined_symbols=%s --model_type=%s'\n","cmd = input_argument%(input_file, model_name, vocab_size,user_defined_symbols, model_type)\n","\n","spm.SentencePieceTrainer.Train(cmd)\n","\n","sp = spm.SentencePieceProcessor()\n","sp.Load(\"subword_kor.model\")\n","wp = sp.EncodeAsPieces(\"하늘을 우러러\")\n","id = sp.EncodeAsIds(\"하늘을 우러러\")\n","print(wp)\n","print(id)\n","\n","wp2snt= sp.DecodePieces(wp)\n","id2snt = sp.DecodeIds(id)\n","print(wp2snt)\n","print(id2snt)\n","\n","print(\"Vocab. Size =\",sp.GetPieceSize())\n","print(sp.IdToPiece(58))\n","print(sp.PieceToId('하'))"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"Ybah5Al8iIQ5"},"outputs":[],"source":[]}],"metadata":{"colab":{"provenance":[]},"kernelspec":{"display_name":"Python 3","name":"python3"}},"nbformat":4,"nbformat_minor":0}